---
# Page meta info, like heading, footer text and nav links
pageInfo:
  title: l1.divix.biz Links
  description: These Links use l1.divix.biz
  navLinks:
    - title: Private-l1.divix.biz Links
      path: "/"

# Optional app settings and configuration
appConfig:
  cssThemes: ["nord-frost-tl"]
  theme: nord-frost
  layout: auto
  iconSize: medium

# Main content - An array of sections, each containing an array of items
sections:
  - name: Media & Entertainment
    items:
      - title: Plex
        description: Plex Media Server TNFS1
        icon: plex.png
        url: https://plex.l1.divix.biz
        target: newtab
        statusCheck: true
        #statusCheckUrl: http://10.1.1.75:32400/identity
        statusCheckUrl: https://plex.l1.divix.biz/identity
        statusCheckAllowInsecure: true
        id: 0_l1db_plex
      - title: Immich
        description: IMMICH Photo Server TNFS1
        icon: immich.png
        url: https://immich.l1.divix.biz
        target: newtab
        statusCheck: true
        statusCheckAllowInsecure: true
        id: 0_l1db_immich

    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    icon: fas fa-photo-video
  - name: Home Control
    icon: fas fa-house-signal
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: HomeAssistant
        description: Home Assistant (tnhl02|haos)
        icon: home-assistant.png
        url: https://hass.l1.divix.biz
        target: newtab
        statusCheck: true
        id: 0_l1db_haos
      - title: Frigate (75)
        description: Frigate VM (TNFS1)
        icon: frigate.png
        url: https://frigate.l1.divix.biz
        target: newtab
        statusCheck: true
        id: 0_l1db_frigate
      - title: Frigate:go2rtc (75)
        description: Frigate:go2rtc VM (TNFS1)
        icon: go2rtc.png
        url: https://go2rtc.l1.divix.biz
        target: newtab
        statusCheck: true
        id: 0_l1db_frigate_go2rtc

  - name: Productivity
    icon: fas fa-bookmark
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: n8n
        description: n8n Workflow Automation
        icon: n8n.png
        backgroundColor: "transparent"
        url: https://n8n.l1.divix.biz
        target: newtab
        statusCheck: true
        statusCheckUrl: https://n8n.l1.divix.biz/healthz
        id: 0_l1db_n8n
      - title: AppSmith
        description: AppSmith App Dev
        icon: appsmith-blue-tr.png
        backgroundColor: "transparent"
        url: https://appsmith.l1.divix.biz
        target: newtab
        statusCheck: true
        statusCheckUrl: https://appsmith.l1.divix.biz
        id: 0_l1db_appsmith
      - title: OpenWebUI
        description: OpenWebUI AI Chatbot
        icon: open-webui-light.png
        backgroundColor: "transparent"
        url: https://openwebui.l1.divix.biz
        target: newtab
        statusCheck: true
        statusCheckUrl: "http://10.1.1.75:3000"
        id: 0_l1db_openwebui
      - title: PGAdmin
        description: PGAdmin PostgreSQL Management
        icon: pgadmin.png
        backgroundColor: "transparent"
        url: https://pgadmin.l1.divix.biz/browser/
        target: newtab
        statusCheck: true
        statusCheckUrl: "http://10.1.1.74:5050/misc/ping"
        id: 0_l1db_pgadmin
      - title: Moodle
        description: Moodle Learning Management System
        icon: moodle.png
        backgroundColor: "transparent"
        url: https://moodle.l1.divix.biz
        target: newtab
        statusCheck: true
        statusCheckUrl: "http://10.1.1.74:5050/misc/ping"
        id: 0_l1db_moodle

      - title: Plane
        description: Trouble Ticket Management
        icon: plane-trans.png
        backgroundColor: "transparent"
        url: https://plane.l1.divix.biz
        target: newtab
        statusCheck: true
        statusCheckUrl: "http://10.1.1.74:8085"
        id: 0_l1db_plane

  - name: Dashy Docs
    icon: far fa-rocket
    displayData:
      sortBy: default
      rows: 1
      cols: 1
      collapsed: false
      hideForGuests: false
    items:
      - title: GitHub
        description: Source Code, Issues and Pull Requests
        icon: fab fa-github-alt
        url: https://github.com/lissy93/dashy
        target: newtab
        id: 0_l1db_github
      - title: Docs
        description: Configuring & Usage Documentation
        icon: far fa-book
        url: https://dashy.to/docs
        target: newtab
        provider: Dashy.to
        statusCheck: true
        id: 1_l1db_docs
      - title: WalkXCode GH
        description: Dashboard Icon List
        icon: far fa-rocket
        url: https://github.com/walkxcode/dashboard-icons
        target: newtab
        id: 2_l1db_walkxcodegh
      - title: WalkXCode Icons
        description: Page to Display All Icons
        icon: far fa-rocket
        url: https://github.com/walkxcode/dashboard-icons/blob/main/ICONS.md
        target: newtab
        id: 3_l1db_walkxcodeicons
      - title: FontAwesome Icons
        description: Searchable Font Awesome Icon Library
        icon: si-fontawesome
        url: https://fontawesome.com/icons
        target: newtab
        id: 4_l1db_fontawesomeicons
      - title: SimpleIcons
        description: Searchable Icon Library
        icon: si-simpleicons
        url: https://simpleicons.org/
        target: newtab
        statusCheckUrl: https://simpleicons.org/
        statusCheck: true
        id: 5_l1db_simpleicons
      - title: Ex Conf.YML
        description: Example Config Files for Dashy
        icon: si-yaml
        url: https://gist.github.com/Lissy93/000f712a5ce98f212817d20bc16bab10
        target: newtab
        id: 6_l1db_exconfyml
      - title: Sub-Pages Issue
        url: https://github.com/Lissy93/dashy/issues/1258
        target: newtab
        id: 7_l1db_subpagesissue
