# Environment Vars in Use
# $TZ : The timezone we run in. Format American/Chicago
# $DOCKERDIR : Usually the divtools/docker dir
# $DOCKERDATADIR: Usually the /opt dir
# $HOSTNAME: defined in .env
# $GF_SECURITY_ADMIN_USER: defined in .env (default is "admin")
# $GF_SECURITY_ADMIN_PASSWORD: defined in .env
# Section Order: CIRPNVEUE
#

# To Start n8n, run:
#  dcup n8n
#  dcup --profile n8n

name: n8n

services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678" # n8n web UI port; change if needed
    networks:
      - n8n-network
    profiles: [n8n]
    environment:
      - TZ=$TZ
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_BASIC_AUTH_ACTIVE=true # Enable basic auth (recommended)
      - N8N_BASIC_AUTH_USER=/run/secrets/n8n-admin-username
      - N8N_BASIC_AUTH_PASSWORD=/run/secrets/n8n-admin-password
      - N8N_HOST=n8n.${DOMAINNAME_2} # Or your domain
      - N8N_PORT=5678
      - N8N_PROTOCOL=http # Use https if behind a reverse proxy
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - N8N_RUNNERS_ENABLED=true
      - WEBHOOK_URL=http://n8n.${DOMAINNAME_2}:5678/ # Adjust for your setup
      - N8N_SECURE_COOKIE=false
      ### DB: SQLITE
      #- DB_SQLITE_POOL_SIZE=5
      ### DB: Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=/run/secrets/n8n-postgres-db-password
    volumes:
      - $DOCKERDATADIR/n8n/data:/home/node/.n8n # Location for SQLite DB, Encryption Keyu
      - $DOCKERDATADIR/n8n/files:/files # Local dir shared between n8n and Host
    secrets:
      - n8n-admin-username
      - n8n-admin-password
      - n8n-postgres-db-password
    depends_on:
      - postgres

  # Postgres DB
  postgres:
    container_name: n8n-postgres
    image: docker.io/postgres:16
    restart: unless-stopped
    networks:
      - n8n-network
    profiles: [n8n]
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=/run/secrets/n8n-postgres-db-password
      - POSTGRES_DB=n8n
    volumes:
      - $DOCKERDATADIR/n8n/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 5s
      retries: 10
    secrets:
      - n8n-postgres-db-password
